# Exercise 3
Given this toy dataset on the size of a rectangle over time, calculate the 10 minute rolling average of the __area__ of the rectangle. If there is less than ten minutes worth of data just use all of the data which is available to you.

In [2]:
import pandas as pd
import numpy as np
from datetime import datetime

date_ranges=pd.date_range(start='11/4/2019', end='11/05/2019', freq='Min')

df = pd.DataFrame({"length":np.random.randint(0,50,size=(len(date_ranges))),
                   "width":np.random.randint(0,50,size=(len(date_ranges)))}, index=date_ranges)
df.head()

length  width
2019-11-04 00:00:00       2     16
2019-11-04 00:01:00      43     19
2019-11-04 00:02:00      21     42
2019-11-04 00:03:00      14     45
2019-11-04 00:04:00      17     44

In [7]:
df["area"]=df["length"]*df["width"]

def do_mean_calc(ary):
    print(ary)
    return np.mean(ary)

df["area"].rolling(10,min_periods=1).apply(do_mean_calc)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:7: FutureWarning: Currently, 'apply' passes the values as ndarrays to the applied function. In the future, this will change to passing it as Series objects. You need to specify 'raw=True' to keep the current behaviour, and you can pass 'raw=False' to silence this warning
  import sys


[2.]
[ 2. 43.]
[ 2. 43. 21.]
[ 2. 43. 21. 14.]
[ 2. 43. 21. 14. 17.]
[ 2. 43. 21. 14. 17. 35.]
[ 2. 43. 21. 14. 17. 35. 31.]
[ 2. 43. 21. 14. 17. 35. 31. 42.]
[ 2. 43. 21. 14. 17. 35. 31. 42.  8.]
[ 2. 43. 21. 14. 17. 35. 31. 42.  8. 10.]
[43. 21. 14. 17. 35. 31. 42.  8. 10. 16.]
[21. 14. 17. 35. 31. 42.  8. 10. 16. 37.]
[14. 17. 35. 31. 42.  8. 10. 16. 37. 46.]
[17. 35. 31. 42.  8. 10. 16. 37. 46. 49.]
[35. 31. 42.  8. 10. 16. 37. 46. 49. 26.]
[31. 42.  8. 10. 16. 37. 46. 49. 26. 21.]
[42.  8. 10. 16. 37. 46. 49. 26. 21.  4.]
[ 8. 10. 16. 37. 46. 49. 26. 21.  4.  8.]
[10. 16. 37. 46. 49. 26. 21.  4.  8. 16.]
[16. 37. 46. 49. 26. 21.  4.  8. 16. 42.]
[37. 46. 49. 26. 21.  4.  8. 16. 42. 48.]
[46. 49. 26. 21.  4.  8. 16. 42. 48. 43.]
[49. 26. 21.  4.  8. 16. 42. 48. 43.  7.]
[26. 21.  4.  8. 16. 42. 48. 43.  7. 44.]
[21.  4.  8. 16. 42. 48. 43.  7. 44. 49.]
[ 4.  8. 16. 42. 48. 43.  7. 44. 49. 17.]
[ 8. 16. 42. 48. 43.  7. 44. 49. 17. 49.]
[16. 42. 48. 43.  7. 44. 49. 17. 49. 49.]
[42. 

[47.  5.  9. 24. 43.  3. 27.  4. 26. 27.]
[ 5.  9. 24. 43.  3. 27.  4. 26. 27.  7.]
[ 9. 24. 43.  3. 27.  4. 26. 27.  7. 28.]
[24. 43.  3. 27.  4. 26. 27.  7. 28. 24.]
[43.  3. 27.  4. 26. 27.  7. 28. 24. 44.]
[ 3. 27.  4. 26. 27.  7. 28. 24. 44. 49.]
[27.  4. 26. 27.  7. 28. 24. 44. 49.  5.]
[ 4. 26. 27.  7. 28. 24. 44. 49.  5. 47.]
[26. 27.  7. 28. 24. 44. 49.  5. 47.  4.]
[27.  7. 28. 24. 44. 49.  5. 47.  4. 17.]
[ 7. 28. 24. 44. 49.  5. 47.  4. 17. 48.]
[28. 24. 44. 49.  5. 47.  4. 17. 48. 27.]
[24. 44. 49.  5. 47.  4. 17. 48. 27. 39.]
[44. 49.  5. 47.  4. 17. 48. 27. 39. 44.]
[49.  5. 47.  4. 17. 48. 27. 39. 44. 23.]
[ 5. 47.  4. 17. 48. 27. 39. 44. 23. 16.]
[47.  4. 17. 48. 27. 39. 44. 23. 16.  8.]
[ 4. 17. 48. 27. 39. 44. 23. 16.  8. 24.]
[17. 48. 27. 39. 44. 23. 16.  8. 24. 15.]
[48. 27. 39. 44. 23. 16.  8. 24. 15. 30.]
[27. 39. 44. 23. 16.  8. 24. 15. 30. 43.]
[39. 44. 23. 16.  8. 24. 15. 30. 43.  3.]
[44. 23. 16.  8. 24. 15. 30. 43.  3. 17.]
[23. 16.  8. 24. 15. 30. 43.  3. 1

[ 6.  5. 10. 39. 45. 48.  4. 15. 16. 28.]
[ 5. 10. 39. 45. 48.  4. 15. 16. 28. 31.]
[10. 39. 45. 48.  4. 15. 16. 28. 31. 35.]
[39. 45. 48.  4. 15. 16. 28. 31. 35.  9.]
[45. 48.  4. 15. 16. 28. 31. 35.  9. 13.]
[48.  4. 15. 16. 28. 31. 35.  9. 13. 18.]
[ 4. 15. 16. 28. 31. 35.  9. 13. 18. 42.]
[15. 16. 28. 31. 35.  9. 13. 18. 42. 16.]
[16. 28. 31. 35.  9. 13. 18. 42. 16. 47.]
[28. 31. 35.  9. 13. 18. 42. 16. 47.  2.]
[31. 35.  9. 13. 18. 42. 16. 47.  2. 34.]
[35.  9. 13. 18. 42. 16. 47.  2. 34. 17.]
[ 9. 13. 18. 42. 16. 47.  2. 34. 17. 27.]
[13. 18. 42. 16. 47.  2. 34. 17. 27. 42.]
[18. 42. 16. 47.  2. 34. 17. 27. 42. 12.]
[42. 16. 47.  2. 34. 17. 27. 42. 12. 48.]
[16. 47.  2. 34. 17. 27. 42. 12. 48. 24.]
[47.  2. 34. 17. 27. 42. 12. 48. 24.  3.]
[ 2. 34. 17. 27. 42. 12. 48. 24.  3. 26.]
[34. 17. 27. 42. 12. 48. 24.  3. 26. 23.]
[17. 27. 42. 12. 48. 24.  3. 26. 23. 44.]
[27. 42. 12. 48. 24.  3. 26. 23. 44.  8.]
[42. 12. 48. 24.  3. 26. 23. 44.  8. 41.]
[12. 48. 24.  3. 26. 23. 44.  8. 4

[40.  0. 25. 44.  8. 44. 16. 13. 30. 45.]
[ 0. 25. 44.  8. 44. 16. 13. 30. 45. 35.]
[25. 44.  8. 44. 16. 13. 30. 45. 35.  8.]
[44.  8. 44. 16. 13. 30. 45. 35.  8. 34.]
[ 8. 44. 16. 13. 30. 45. 35.  8. 34. 48.]
[44. 16. 13. 30. 45. 35.  8. 34. 48. 35.]
[16. 13. 30. 45. 35.  8. 34. 48. 35. 17.]
[13. 30. 45. 35.  8. 34. 48. 35. 17. 10.]
[30. 45. 35.  8. 34. 48. 35. 17. 10. 31.]
[45. 35.  8. 34. 48. 35. 17. 10. 31.  7.]
[35.  8. 34. 48. 35. 17. 10. 31.  7. 18.]
[ 8. 34. 48. 35. 17. 10. 31.  7. 18. 41.]
[34. 48. 35. 17. 10. 31.  7. 18. 41. 11.]
[48. 35. 17. 10. 31.  7. 18. 41. 11. 15.]
[35. 17. 10. 31.  7. 18. 41. 11. 15. 11.]
[17. 10. 31.  7. 18. 41. 11. 15. 11. 31.]
[10. 31.  7. 18. 41. 11. 15. 11. 31. 10.]
[31.  7. 18. 41. 11. 15. 11. 31. 10. 27.]
[ 7. 18. 41. 11. 15. 11. 31. 10. 27. 28.]
[18. 41. 11. 15. 11. 31. 10. 27. 28.  5.]
[41. 11. 15. 11. 31. 10. 27. 28.  5. 35.]
[11. 15. 11. 31. 10. 27. 28.  5. 35. 16.]
[15. 11. 31. 10. 27. 28.  5. 35. 16. 33.]
[11. 31. 10. 27. 28.  5. 35. 16. 3

[ 0. 48. 49. 26. 20. 24. 27. 44. 25.  4.]
[48. 49. 26. 20. 24. 27. 44. 25.  4.  7.]
[49. 26. 20. 24. 27. 44. 25.  4.  7.  9.]
[26. 20. 24. 27. 44. 25.  4.  7.  9. 27.]
[20. 24. 27. 44. 25.  4.  7.  9. 27.  2.]
[24. 27. 44. 25.  4.  7.  9. 27.  2.  1.]
[27. 44. 25.  4.  7.  9. 27.  2.  1. 23.]
[44. 25.  4.  7.  9. 27.  2.  1. 23. 16.]
[25.  4.  7.  9. 27.  2.  1. 23. 16.  4.]
[ 4.  7.  9. 27.  2.  1. 23. 16.  4. 45.]
[ 7.  9. 27.  2.  1. 23. 16.  4. 45. 46.]
[ 9. 27.  2.  1. 23. 16.  4. 45. 46. 31.]
[27.  2.  1. 23. 16.  4. 45. 46. 31.  4.]
[ 2.  1. 23. 16.  4. 45. 46. 31.  4. 46.]
[ 1. 23. 16.  4. 45. 46. 31.  4. 46.  1.]
[23. 16.  4. 45. 46. 31.  4. 46.  1. 24.]
[16.  4. 45. 46. 31.  4. 46.  1. 24. 11.]
[ 4. 45. 46. 31.  4. 46.  1. 24. 11. 39.]
[45. 46. 31.  4. 46.  1. 24. 11. 39. 18.]
[46. 31.  4. 46.  1. 24. 11. 39. 18. 18.]
[31.  4. 46.  1. 24. 11. 39. 18. 18. 38.]
[ 4. 46.  1. 24. 11. 39. 18. 18. 38. 28.]
[46.  1. 24. 11. 39. 18. 18. 38. 28. 42.]
[ 1. 24. 11. 39. 18. 18. 38. 28. 4

[27. 14. 37. 20. 31. 49. 17. 19. 12. 10.]
[14. 37. 20. 31. 49. 17. 19. 12. 10. 17.]
[37. 20. 31. 49. 17. 19. 12. 10. 17. 18.]
[20. 31. 49. 17. 19. 12. 10. 17. 18. 37.]
[31. 49. 17. 19. 12. 10. 17. 18. 37. 22.]
[49. 17. 19. 12. 10. 17. 18. 37. 22. 16.]
[17. 19. 12. 10. 17. 18. 37. 22. 16. 38.]
[19. 12. 10. 17. 18. 37. 22. 16. 38. 20.]
[12. 10. 17. 18. 37. 22. 16. 38. 20.  8.]
[10. 17. 18. 37. 22. 16. 38. 20.  8. 16.]
[17. 18. 37. 22. 16. 38. 20.  8. 16. 47.]
[18. 37. 22. 16. 38. 20.  8. 16. 47. 18.]
[37. 22. 16. 38. 20.  8. 16. 47. 18.  0.]
[22. 16. 38. 20.  8. 16. 47. 18.  0.  2.]
[16. 38. 20.  8. 16. 47. 18.  0.  2. 44.]
[38. 20.  8. 16. 47. 18.  0.  2. 44.  5.]
[20.  8. 16. 47. 18.  0.  2. 44.  5. 18.]
[ 8. 16. 47. 18.  0.  2. 44.  5. 18. 22.]
[16. 47. 18.  0.  2. 44.  5. 18. 22. 21.]
[47. 18.  0.  2. 44.  5. 18. 22. 21. 46.]
[18.  0.  2. 44.  5. 18. 22. 21. 46. 29.]
[ 0.  2. 44.  5. 18. 22. 21. 46. 29.  1.]
[ 2. 44.  5. 18. 22. 21. 46. 29.  1. 38.]
[44.  5. 18. 22. 21. 46. 29.  1. 3

[20. 39. 47. 25.  0.  3. 23. 18.  6.  5.]
[39. 47. 25.  0.  3. 23. 18.  6.  5. 31.]
[47. 25.  0.  3. 23. 18.  6.  5. 31. 11.]
[25.  0.  3. 23. 18.  6.  5. 31. 11. 46.]
[ 0.  3. 23. 18.  6.  5. 31. 11. 46. 34.]
[ 3. 23. 18.  6.  5. 31. 11. 46. 34. 47.]
[23. 18.  6.  5. 31. 11. 46. 34. 47. 45.]
[18.  6.  5. 31. 11. 46. 34. 47. 45. 22.]
[ 6.  5. 31. 11. 46. 34. 47. 45. 22.  0.]
[ 5. 31. 11. 46. 34. 47. 45. 22.  0. 41.]
[31. 11. 46. 34. 47. 45. 22.  0. 41. 24.]
[11. 46. 34. 47. 45. 22.  0. 41. 24. 40.]
[46. 34. 47. 45. 22.  0. 41. 24. 40. 28.]
[34. 47. 45. 22.  0. 41. 24. 40. 28. 27.]
[47. 45. 22.  0. 41. 24. 40. 28. 27. 31.]
[45. 22.  0. 41. 24. 40. 28. 27. 31. 38.]
[22.  0. 41. 24. 40. 28. 27. 31. 38. 18.]
[ 0. 41. 24. 40. 28. 27. 31. 38. 18. 46.]
[41. 24. 40. 28. 27. 31. 38. 18. 46. 46.]
[24. 40. 28. 27. 31. 38. 18. 46. 46. 23.]
[40. 28. 27. 31. 38. 18. 46. 46. 23. 45.]
[28. 27. 31. 38. 18. 46. 46. 23. 45. 49.]
[27. 31. 38. 18. 46. 46. 23. 45. 49.  4.]
[31. 38. 18. 46. 46. 23. 45. 49.  

[20.  5. 43. 10. 27. 47.  2. 31.  7. 38.]
[ 5. 43. 10. 27. 47.  2. 31.  7. 38.  5.]
[43. 10. 27. 47.  2. 31.  7. 38.  5.  1.]
[10. 27. 47.  2. 31.  7. 38.  5.  1.  7.]
[27. 47.  2. 31.  7. 38.  5.  1.  7. 38.]
[47.  2. 31.  7. 38.  5.  1.  7. 38. 11.]
[ 2. 31.  7. 38.  5.  1.  7. 38. 11. 23.]
[31.  7. 38.  5.  1.  7. 38. 11. 23. 29.]
[ 7. 38.  5.  1.  7. 38. 11. 23. 29. 17.]
[38.  5.  1.  7. 38. 11. 23. 29. 17. 32.]
[ 5.  1.  7. 38. 11. 23. 29. 17. 32. 41.]
[ 1.  7. 38. 11. 23. 29. 17. 32. 41.  8.]
[ 7. 38. 11. 23. 29. 17. 32. 41.  8. 36.]
[38. 11. 23. 29. 17. 32. 41.  8. 36. 27.]
[11. 23. 29. 17. 32. 41.  8. 36. 27. 17.]
[23. 29. 17. 32. 41.  8. 36. 27. 17. 12.]
[29. 17. 32. 41.  8. 36. 27. 17. 12.  9.]
[17. 32. 41.  8. 36. 27. 17. 12.  9. 19.]
[32. 41.  8. 36. 27. 17. 12.  9. 19. 40.]
[41.  8. 36. 27. 17. 12.  9. 19. 40. 49.]
[ 8. 36. 27. 17. 12.  9. 19. 40. 49.  7.]
[36. 27. 17. 12.  9. 19. 40. 49.  7. 28.]
[27. 17. 12.  9. 19. 40. 49.  7. 28.  2.]
[17. 12.  9. 19. 40. 49.  7. 28.  

[49.  6. 19. 17. 27. 12.  7.  7. 49. 26.]
[ 6. 19. 17. 27. 12.  7.  7. 49. 26.  2.]
[19. 17. 27. 12.  7.  7. 49. 26.  2. 15.]
[17. 27. 12.  7.  7. 49. 26.  2. 15. 37.]
[27. 12.  7.  7. 49. 26.  2. 15. 37. 40.]
[12.  7.  7. 49. 26.  2. 15. 37. 40. 18.]
[ 7.  7. 49. 26.  2. 15. 37. 40. 18. 46.]
[ 7. 49. 26.  2. 15. 37. 40. 18. 46. 48.]
[49. 26.  2. 15. 37. 40. 18. 46. 48. 27.]
[26.  2. 15. 37. 40. 18. 46. 48. 27. 14.]
[ 2. 15. 37. 40. 18. 46. 48. 27. 14.  8.]
[15. 37. 40. 18. 46. 48. 27. 14.  8. 43.]
[37. 40. 18. 46. 48. 27. 14.  8. 43. 31.]
[40. 18. 46. 48. 27. 14.  8. 43. 31. 47.]
[18. 46. 48. 27. 14.  8. 43. 31. 47. 30.]
[46. 48. 27. 14.  8. 43. 31. 47. 30. 22.]
[48. 27. 14.  8. 43. 31. 47. 30. 22. 49.]
[27. 14.  8. 43. 31. 47. 30. 22. 49.  9.]
[14.  8. 43. 31. 47. 30. 22. 49.  9.  2.]
[ 8. 43. 31. 47. 30. 22. 49.  9.  2. 37.]
[43. 31. 47. 30. 22. 49.  9.  2. 37.  2.]
[31. 47. 30. 22. 49.  9.  2. 37.  2. 34.]
[47. 30. 22. 49.  9.  2. 37.  2. 34. 48.]
[30. 22. 49.  9.  2. 37.  2. 34. 4

[ 1.  3. 37.  5. 45. 38. 47.  0. 31. 12.]
[ 3. 37.  5. 45. 38. 47.  0. 31. 12. 46.]
[37.  5. 45. 38. 47.  0. 31. 12. 46. 23.]
[ 5. 45. 38. 47.  0. 31. 12. 46. 23.  4.]
[45. 38. 47.  0. 31. 12. 46. 23.  4. 24.]
[38. 47.  0. 31. 12. 46. 23.  4. 24. 37.]
[47.  0. 31. 12. 46. 23.  4. 24. 37. 43.]
[ 0. 31. 12. 46. 23.  4. 24. 37. 43.  1.]
[31. 12. 46. 23.  4. 24. 37. 43.  1. 48.]
[12. 46. 23.  4. 24. 37. 43.  1. 48. 37.]
[46. 23.  4. 24. 37. 43.  1. 48. 37. 25.]
[23.  4. 24. 37. 43.  1. 48. 37. 25. 43.]
[ 4. 24. 37. 43.  1. 48. 37. 25. 43. 39.]
[24. 37. 43.  1. 48. 37. 25. 43. 39.  4.]
[37. 43.  1. 48. 37. 25. 43. 39.  4. 36.]
[43.  1. 48. 37. 25. 43. 39.  4. 36. 40.]
[ 1. 48. 37. 25. 43. 39.  4. 36. 40. 28.]
[48. 37. 25. 43. 39.  4. 36. 40. 28.  2.]
[37. 25. 43. 39.  4. 36. 40. 28.  2. 48.]
[25. 43. 39.  4. 36. 40. 28.  2. 48. 34.]
[43. 39.  4. 36. 40. 28.  2. 48. 34.  4.]
[39.  4. 36. 40. 28.  2. 48. 34.  4. 28.]
[ 4. 36. 40. 28.  2. 48. 34.  4. 28. 14.]
[36. 40. 28.  2. 48. 34.  4. 28. 1

[ 527.   48.   98. 1125.   64.   84.  837.  125. 1104. 1505.]
[  48.   98. 1125.   64.   84.  837.  125. 1104. 1505. 1444.]
[  98. 1125.   64.   84.  837.  125. 1104. 1505. 1444.  576.]
[1125.   64.   84.  837.  125. 1104. 1505. 1444.  576.  434.]
[  64.   84.  837.  125. 1104. 1505. 1444.  576.  434.  455.]
[  84.  837.  125. 1104. 1505. 1444.  576.  434.  455.  851.]
[ 837.  125. 1104. 1505. 1444.  576.  434.  455.  851. 1156.]
[ 125. 1104. 1505. 1444.  576.  434.  455.  851. 1156.  240.]
[1104. 1505. 1444.  576.  434.  455.  851. 1156.  240.  828.]
[1505. 1444.  576.  434.  455.  851. 1156.  240.  828.  725.]
[1444.  576.  434.  455.  851. 1156.  240.  828.  725. 1568.]
[ 576.  434.  455.  851. 1156.  240.  828.  725. 1568.   29.]
[ 434.  455.  851. 1156.  240.  828.  725. 1568.   29.   46.]
[ 455.  851. 1156.  240.  828.  725. 1568.   29.   46. 1457.]
[ 851. 1156.  240.  828.  725. 1568.   29.   46. 1457.  230.]
[1156.  240.  828.  725. 1568.   29.   46. 1457.  230.  270.]
[ 240.  

[ 546.  261.   76. 1457.  943.   20. 1189. 1107.    0.  380.]
[ 261.   76. 1457.  943.   20. 1189. 1107.    0.  380.  420.]
[  76. 1457.  943.   20. 1189. 1107.    0.  380.  420.    2.]
[1457.  943.   20. 1189. 1107.    0.  380.  420.    2.  280.]
[ 943.   20. 1189. 1107.    0.  380.  420.    2.  280.  136.]
[  20. 1189. 1107.    0.  380.  420.    2.  280.  136. 1230.]
[1189. 1107.    0.  380.  420.    2.  280.  136. 1230.  703.]
[1107.    0.  380.  420.    2.  280.  136. 1230.  703.  561.]
[   0.  380.  420.    2.  280.  136. 1230.  703.  561. 1739.]
[ 380.  420.    2.  280.  136. 1230.  703.  561. 1739.  204.]
[ 420.    2.  280.  136. 1230.  703.  561. 1739.  204.  676.]
[   2.  280.  136. 1230.  703.  561. 1739.  204.  676.  390.]
[ 280.  136. 1230.  703.  561. 1739.  204.  676.  390.  816.]
[ 136. 1230.  703.  561. 1739.  204.  676.  390.  816. 1564.]
[1230.  703.  561. 1739.  204.  676.  390.  816. 1564.  297.]
[ 703.  561. 1739.  204.  676.  390.  816. 1564.  297.   57.]
[ 561. 1

[ 561.  286.  176.  725.  630. 1125.  912.   63.   55.  351.]
[ 286.  176.  725.  630. 1125.  912.   63.   55.  351.  182.]
[ 176.  725.  630. 1125.  912.   63.   55.  351.  182.   52.]
[ 725.  630. 1125.  912.   63.   55.  351.  182.   52.    9.]
[ 630. 1125.  912.   63.   55.  351.  182.   52.    9.  870.]
[1125.  912.   63.   55.  351.  182.   52.    9.  870. 1344.]
[ 912.   63.   55.  351.  182.   52.    9.  870. 1344.  702.]
[  63.   55.  351.  182.   52.    9.  870. 1344.  702.  736.]
[  55.  351.  182.   52.    9.  870. 1344.  702.  736.  242.]
[ 351.  182.   52.    9.  870. 1344.  702.  736.  242.   66.]
[ 182.   52.    9.  870. 1344.  702.  736.  242.   66. 1419.]
[  52.    9.  870. 1344.  702.  736.  242.   66. 1419.   60.]
[   9.  870. 1344.  702.  736.  242.   66. 1419.   60.   50.]
[ 870. 1344.  702.  736.  242.   66. 1419.   60.   50.   86.]
[1344.  702.  736.  242.   66. 1419.   60.   50.   86. 1591.]
[ 702.  736.  242.   66. 1419.   60.   50.   86. 1591.  384.]
[ 736.  

[ 150.  396.    0.  510.  364.    0. 2016.  336.  765.  102.]
[ 396.    0.  510.  364.    0. 2016.  336.  765.  102.  629.]
[   0.  510.  364.    0. 2016.  336.  765.  102.  629.  544.]
[ 510.  364.    0. 2016.  336.  765.  102.  629.  544.  320.]
[ 364.    0. 2016.  336.  765.  102.  629.  544.  320.  144.]
[   0. 2016.  336.  765.  102.  629.  544.  320.  144.  330.]
[2016.  336.  765.  102.  629.  544.  320.  144.  330.  243.]
[ 336.  765.  102.  629.  544.  320.  144.  330.  243. 1170.]
[ 765.  102.  629.  544.  320.  144.  330.  243. 1170.   55.]
[ 102.  629.  544.  320.  144.  330.  243. 1170.   55.  340.]
[ 629.  544.  320.  144.  330.  243. 1170.   55.  340.   43.]
[ 544.  320.  144.  330.  243. 1170.   55.  340.   43.  168.]
[ 320.  144.  330.  243. 1170.   55.  340.   43.  168.  117.]
[ 144.  330.  243. 1170.   55.  340.   43.  168.  117. 1584.]
[ 330.  243. 1170.   55.  340.   43.  168.  117. 1584. 1333.]
[ 243. 1170.   55.  340.   43.  168.  117. 1584. 1333.  310.]
[1170.  

[ 232.  817.  124. 1880. 1290.  462. 1960.  216.   42.  148.]
[ 817.  124. 1880. 1290.  462. 1960.  216.   42.  148.   60.]
[ 124. 1880. 1290.  462. 1960.  216.   42.  148.   60. 1394.]
[1880. 1290.  462. 1960.  216.   42.  148.   60. 1394.  192.]
[1290.  462. 1960.  216.   42.  148.   60. 1394.  192.  144.]
[ 462. 1960.  216.   42.  148.   60. 1394.  192.  144.   76.]
[1960.  216.   42.  148.   60. 1394.  192.  144.   76. 1332.]
[ 216.   42.  148.   60. 1394.  192.  144.   76. 1332.  300.]
[  42.  148.   60. 1394.  192.  144.   76. 1332.  300.  546.]
[ 148.   60. 1394.  192.  144.   76. 1332.  300.  546.  760.]
[  60. 1394.  192.  144.   76. 1332.  300.  546.  760.  440.]
[1394.  192.  144.   76. 1332.  300.  546.  760.  440. 1230.]
[ 192.  144.   76. 1332.  300.  546.  760.  440. 1230.  329.]
[ 144.   76. 1332.  300.  546.  760.  440. 1230.  329.  616.]
[  76. 1332.  300.  546.  760.  440. 1230.  329.  616.  390.]
[1332.  300.  546.  760.  440. 1230.  329.  616.  390.  480.]
[ 300.  

[ 384.  880.  182.  580.  210.  720. 1845.  529.  840.  378.]
[ 880.  182.  580.  210.  720. 1845.  529.  840.  378.  940.]
[ 182.  580.  210.  720. 1845.  529.  840.  378.  940.   45.]
[ 580.  210.  720. 1845.  529.  840.  378.  940.   45.  570.]
[ 210.  720. 1845.  529.  840.  378.  940.   45.  570.  680.]
[ 720. 1845.  529.  840.  378.  940.   45.  570.  680. 1920.]
[1845.  529.  840.  378.  940.   45.  570.  680. 1920. 1088.]
[ 529.  840.  378.  940.   45.  570.  680. 1920. 1088.  108.]
[ 840.  378.  940.   45.  570.  680. 1920. 1088.  108.  451.]
[ 378.  940.   45.  570.  680. 1920. 1088.  108.  451.   77.]
[ 940.   45.  570.  680. 1920. 1088.  108.  451.   77.    0.]
[  45.  570.  680. 1920. 1088.  108.  451.   77.    0.  336.]
[ 570.  680. 1920. 1088.  108.  451.   77.    0.  336.   98.]
[ 680. 1920. 1088.  108.  451.   77.    0.  336.   98.  156.]
[1920. 1088.  108.  451.   77.    0.  336.   98.  156.  320.]
[1088.  108.  451.   77.    0.  336.   98.  156.  320.  624.]
[108. 45

[1702.  874.  100.  984.  407. 1247.   31. 1536.  777.  700.]
[ 874.  100.  984.  407. 1247.   31. 1536.  777.  700.  774.]
[ 100.  984.  407. 1247.   31. 1536.  777.  700.  774.  429.]
[ 984.  407. 1247.   31. 1536.  777.  700.  774.  429.   48.]
[ 407. 1247.   31. 1536.  777.  700.  774.  429.   48.  540.]
[1247.   31. 1536.  777.  700.  774.  429.   48.  540.  920.]
[  31. 1536.  777.  700.  774.  429.   48.  540.  920.  728.]
[1536.  777.  700.  774.  429.   48.  540.  920.  728.   52.]
[ 777.  700.  774.  429.   48.  540.  920.  728.   52. 1296.]
[ 700.  774.  429.   48.  540.  920.  728.   52. 1296.  442.]
[ 774.  429.   48.  540.  920.  728.   52. 1296.  442.   76.]
[ 429.   48.  540.  920.  728.   52. 1296.  442.   76.  168.]
[  48.  540.  920.  728.   52. 1296.  442.   76.  168.  280.]
[ 540.  920.  728.   52. 1296.  442.   76.  168.  280. 1092.]
[ 920.  728.   52. 1296.  442.   76.  168.  280. 1092.   38.]
[ 728.   52. 1296.  442.   76.  168.  280. 1092.   38. 1080.]
[  52. 1

length      width        area
2019-11-04 00:00:00   2.000000  16.000000   32.000000
2019-11-04 00:01:00  22.500000  17.500000  424.500000
2019-11-04 00:02:00  22.000000  25.666667  577.000000
2019-11-04 00:03:00  20.000000  30.500000  590.250000
2019-11-04 00:04:00  19.400000  33.200000  621.800000
2019-11-04 00:05:00  22.000000  29.333333  576.500000
2019-11-04 00:06:00  23.285714  29.142857  618.142857
2019-11-04 00:07:00  25.625000  29.250000  698.375000
2019-11-04 00:08:00  23.666667  29.111111  645.666667
2019-11-04 00:09:00  22.300000  27.500000  594.100000
2019-11-04 00:10:00  23.700000  26.400000  598.900000
2019-11-04 00:11:00  23.100000  27.200000  617.100000
2019-11-04 00:12:00  25.600000  23.700000  561.100000
2019-11-04 00:13:00  29.100000  23.000000  684.300000
2019-11-04 00:14:00  30.000000  19.800000  640.700000
2019-11-04 00:15:00  28.600000  20.800000  647.700000
2019-11-04 00:16:00  25.900000  22.900000  580.500000
2019-11-04 00:17:00  22.500000  22.500000  475.300000
2019-11-04 00:18:00  23.300000  22.800000  502.500000
2019-11-04 00:19:00  26.500000  21.900000  506.300000
2019-11-04 00:20:00  29.700000  21.700000  512.700000
2019-11-04 00:21:00  30.300000  19.900000  451.500000
2019-11-04 00:22:00  26.400000  21.600000  436.100000
2019-11-04 00:23:00  25.900000  19.400000  320.300000
2019-11-04 00:24:00  28.200000  19.900000  372.400000
2019-11-04 00:25:00  27.800000  20.800000  379.700000
2019-11-04 00:26:00  32.300000  20.800000  600.200000
2019-11-04 00:27:00  36.400000  22.300000  780.300000
2019-11-04 00:28:00  37.300000  22.800000  820.700000
2019-11-04 00:29:00  33.600000  25.100000  817.400000
...                        ...        ...         ...
2019-11-04 23:31:00  24.900000  26.900000  646.900000
2019-11-04 23:32:00  23.300000  24.700000  542.300000
2019-11-04 23:33:00  26.400000  24.000000  656.200000
2019-11-04 23:34:00  25.100000  22.700000  576.900000
2019-11-04 23:35:00  27.600000  22.200000  672.400000
2019-11-04 23:36:00  26.100000  24.000000  694.300000
2019-11-04 23:37:00  28.400000  22.200000  677.300000
2019-11-04 23:38:00  28.500000  21.600000  655.000000
2019-11-04 23:39:00  30.600000  23.700000  749.500000
2019-11-04 23:40:00  32.100000  23.400000  767.500000
2019-11-04 23:41:00  34.200000  21.300000  767.500000
2019-11-04 23:42:00  33.900000  24.000000  824.200000
2019-11-04 23:43:00  31.200000  21.700000  686.700000
2019-11-04 23:44:00  31.300000  22.000000  697.000000
2019-11-04 23:45:00  29.400000  19.700000  559.700000
2019-11-04 23:46:00  31.200000  21.100000  655.100000
2019-11-04 23:47:00  28.500000  21.300000  651.300000
2019-11-04 23:48:00  25.200000  19.500000  559.200000
2019-11-04 23:49:00  25.600000  20.000000  591.900000
2019-11-04 23:50:00  23.500000  22.100000  587.700000
2019-11-04 23:51:00  23.500000  21.900000  581.100000
2019-11-04 23:52:00  25.100000  20.400000  581.700000
2019-11-04 23:53:00  28.200000  19.800000  604.300000
2019-11-04 23:54:00  27.800000  21.200000  626.500000
2019-11-04 23:55:00  25.700000  21.500000  587.800000
2019-11-04 23:56:00  25.400000  19.400000  506.800000
2019-11-04 23:57:00  28.600000  20.200000  551.600000
2019-11-04 23:58:00  30.900000  20.200000  563.100000
2019-11-04 23:59:00  29.500000  18.900000  481.000000
2019-11-05 00:00:00  31.400000  16.800000  482.000000

[1441 rows x 3 columns]

In [ ]:
# Excercise 3
# Watch out for using rolling() with a dataframe and expecting to get two columns, you won't! It only works
# on single columns
# Make sure you set min_periods=1 or you'll get a bunch of nan's
(df["length"]*df["width"]).rolling(10, min_periods=1).apply(np.nanmean)